# This code was generated by ChatGPT using the following question:
# can you write a python class that runs Conways game of life?  Use Python 3.11.  The program should open a window,
# and display the results for each generation. Please optimize for speed the portion of the code that determines
# if a cell is alive or not.
import tkinter as tk
import numpy as np

class GameOfLife:
    def __init__(self, width, height):
        self.width = width
        self.height = height
        self.grid = np.zeros((width, height), dtype=bool)
        self.window = tk.Tk()
        self.canvas = tk.Canvas(self.window, width=width, height=height)
        self.canvas.pack()
        self.running = False

        self.window.bind('<Button-1>', self.handle_click)
        self.window.bind('<space>', self.toggle_running)
        self.window.bind('<Return>', self.step)

       # Set up initial cells
        self.grid[2][3] = True
        self.grid[3][4] = True
        self.grid[4][2] = True
        self.grid[4][3] = True
        self.grid[4][4] = True
    def handle_click(self, event):
        x = int(event.x)
        y = int(event.y)
        self.grid[x, y] = not self.grid[x, y]
        self.draw_cell(x, y)

    def toggle_running(self, event):
        self.running = not self.running
        if self.running:
            self.run()

    def step(self, event):
        if not self.running:
            self.update_grid()
            self.draw_grid()

    def run(self):
        if self.running:
            self.update_grid()
            self.draw_grid()
            self.window.after(100, self.run)

    def update_grid(self):
        next_grid = np.zeros_like(self.grid)
        for x in range(self.width):
            for y in range(self.height):
                live_neighbors = np.sum(self.grid[max(0, x-1):min(x+2, self.width), max(0, y-1):min(y+2, self.height)]) - self.grid[x, y]
                if self.grid[x, y]:
                    next_grid[x, y] = live_neighbors in (2, 3)
                else:
                    next_grid[x, y] = live_neighbors == 3
        self.grid = next_grid

    def draw_grid(self):
        self.canvas.delete('all')
        for x in range(self.width):
            for y in range(self.height):
                if self.grid[x, y]:
                    self.draw_cell(x, y)

    def draw_cell(self, x, y):
        self.canvas.create_rectangle(x, y, x+1, y+1, fill='black')

    def start(self):
        self.window.mainloop()


# Example usage
if __name__ == '__main__':
    game = GameOfLife(400, 400)  # Specify the width and height of the grid
    game.start()
